# Generated by Django 4.2.3 on 2024-11-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.profile'),
        ),
    ]
